force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <label>Notification__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Drinks_Dispatch_View_Id__c.field-meta.xml
<CustomField>
    <fullName>Drinks_Dispatch_View_Id__c</fullName>
    <label>Drinks Dispatch View Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <label>Event Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Machine_Location__c.field-meta.xml
<CustomField>
    <fullName>Machine_Location__c</fullName>
    <label>Machine Location</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Universal_Player_ID__c.field-meta.xml
<CustomField>
    <fullName>Universal_Player_ID__c</fullName>
    <label>Universal Player ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DrinkDispatchApi.cls
@RestResource(urlMapping = '/NotificationApi/*')
Global with sharing class DrinkDispatchApi {
    @HTTPPost   
    global static String CreateNewNotification(notificationWrapper wrapperObj){
        
        //RestRequest NotificationRequest = RestContext.request;
        
       // String requestBody = NotificationRequest.requestBody.toString();
        
        //Notification__c Notification = (Notification__c) JSON.deserialize(requestBody, Notification__c.class);
        
        Notification__c NotificationObj = new Notification__c();
        
        NotificationObj.Universal_Player_ID__c = wrapperObj.UniversalPlayerId;
        NotificationObj.Drinks_Dispatch_View_Id__c = wrapperObj.DrinksDispatchViewId;
        NotificationObj.Machine_Location__c = wrapperObj.MachineLocation ;
        NotificationObj.Notified__c = wrapperObj.Notified;
        //NotificationObj.Event_Date_Time__c = wrapperObj.EventDateTime;
        
        insert NotificationObj;
        
        return NotificationObj.id;        
    }
    global class notificationWrapper {
        
        public String UniversalPlayerId;
        public Integer DrinksDispatchViewId;
        public String MachineLocation;
        public Boolean Notified;
        //public DateTime EventDateTime;
        
    }
	/*
	@HTTPPost   
    global static String CreateNewNotification(String UniversalPlayerId, 
                                               Integer DrinksDispatchViewId, 
                                               string MachineLocation, 
                                               boolean Notified,
                                               Datetime EventDateTime){
               system.debug('entered');

        system.debug('UniversalPlayerId'+UniversalPlayerId);
        Notification__c NotificationObj = new Notification__c();
        
        NotificationObj.Universal_Player_ID__c = UniversalPlayerId;
        NotificationObj.Drinks_Dispatch_View_Id__c = DrinksDispatchViewId;
        NotificationObj.Machine_Location__c = MachineLocation ;
        NotificationObj.Notified__c = Notified;
        //NotificationObj.Event_Date_Time__c = EventDateTime;
        
        insert NotificationObj;
        
        return NotificationObj.id;*/        
        
    }