force-app/main/default/objects/Canditate__c/Canditate__c.object-meta.xml
<CustomObject>
    <label>Canditate</label>
    <nameField>
        <label>Canditate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canditates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Canditate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Canditates</relationshipLabel>
    <relationshipName>Canditates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PositionCanditateUpdate.cls
public class PositionCanditateUpdate {
    
    public static void CanditateUpdate(){
        
        list<position__c> listpos = new list<position__c>();
        list<canditate__c> canlist = new list<canditate__c>();
              
        for( position__c positionList : listpos){
            
            canditate__c can = new canditate__c();
            can.Name = positionList.Name;
            can.Address__c = positionList.Name;
            can.Id = positionList.Id;            
            canlist.add(can);
        }
        
        Insert canlist;
    }

}